### ISSUE TITLE
Difference between video record on phone?

### ISSUE THREAD

**Issue by daveisfera** [apivideo/api.video-reactnative-live-stream#49]
**Describe the bug**
If we record a video on an iPhone and then stream it to an RTMP server using `ffmpeg`, the video works, but if we send it directly to the RTMP server using this module, it ends up being green. Is there a difference in the codec or way the video is recorded than what the camera app does? The detail that I've noticed is that from the recorded video the NALU Headers are 0x67, 0x68, 0x65, but when using this module, they are 0x27, 0x28, 0x06 so I think that that's the indication of something being different that's related to this issue

**To Reproduce**
1. Stream from module to RTMP server
2. Log NALU Headers
3. Observe difference

**Expected behavior**
Video looks correct from both a recorded file and a stream from the module

**Screenshots**
<img width="614" alt="Screenshot 2022-12-02 at 9 03 06 PM" src="https://user-images.githubusercontent.com/1686193/205421839-25fbec34-608b-4a83-be3a-05b5f3444c2f.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: 16.1.2
 - Browser: Safari
 - Version: 16.1 (18614.2.9.1.12)

**Comment by ThibaultBee** [comment]
Hi,

Do you have logs on your server?
I can't really see with a still picture what is wrong:
- if there are glitches, you may face packet loss (try with a very low bitrate to check)
- if it is just green without glitches, somehow, you miss the UV plan.

In any case, we can't really help you on this.

------------------------
Obviously there are differences between a record and a stream because the constraints are not the same.
I don't know in which audio and video encoder Apple record its video but it is likely to be AVC and AAC such as in live stream. 
The main difference in term of encoder are:
- the bitrate (a stream on an IP network must have a lower bitrate)
- the latency (a live stream must be real time).

There are also differences between containers/packaging. I guess you record in MOV and the live stream is in FLV/RTMP.

For the NALU header, I would recommend to check out in the ISO the purpose of these bits. The NALU type is not a 8-bit value.

**Comment by daveisfera** [comment]
> Do you have logs on your server? I can't really see with a still picture what is wrong:

Yes, this testing is happening all on my local server with both normal and debug logging on with no signs of connection/data flow issues

> * if there are glitches, you may face packet loss (try with a very low bitrate to check)

I've tried multiple bitrates, but still the same issue

> * if it is just green without glitches, somehow, you miss the UV plan.

The video looks "normal" other than everything being green

> Obviously there are differences between a record and a stream because the constraints are not the same. I don't know in which audio and video encoder Apple record its video but it is likely to be AVC and AAC such as in live stream. The main difference in term of encoder are:

Yes, the audio is in AAC for both the recorded file and the stream.

> There are also differences between containers/packaging. I guess you record in MOV and the live stream is in FLV/RTMP.

Yes, you're correct about the containers being used in both cases, but `ffmpeg` then changes the container to FLV/RTMP and everything looks normal, so I believe that indicates that it should be possible to get the video working from the phone to the RTMP server using the stream as well since they should be functionally (if not exactly) identical.

> For the NALU header, I would recommend to check out in the ISO the purpose of these bits. The NALU type is not a 8-bit value.

If you break down the above values of the NALU Headers that I sent, then it appears that the wrong NAL Unit Type is being sent by the streaming app. It's sending a value of 6, when it appears that it should be a value of 5. I'm basing that on what I'm seeing from hardware and `ffmpeg` sending video to the RTMP server and [this document](https://yumichan.net/video-processing/video-compression/introduction-to-h264-nal-unit/#:~:text=First%20Byte%20of%20NALU%3A%20NAL,into%203%20parts%20as%20shown.) so is that something you agree with or do you have any other ideas of what to look into as the cause of the problem?

**Comment by ThibaultBee** [comment]
Well, 6 is the NALU type for SEI. Could you find the IDR frame be right after the SEI?
Anyway, if you have part of the frame, it means that your IDR is found by the decoder.

**Comment by ThibaultBee** [comment]
As the video stream is decoded, the IDR must be present somewhere. I can assure you that IDR is in the stream because even `ffmpeg` found it. They might be an issue with the way you are looking at the stream.

As far as I understand, your issue is on the server side. We can not help you more that what we already did. What is your server?

**Comment by daveisfera** [comment]
Yes, I just verified that an SEI frame is received and then the IDR frame is received. Is it possible to turn off the SEI frame? Or how about only sending it on the first keyframe and then not sending it on the keyframes after that?

**Comment by ThibaultBee** [comment]
No, it is not possible to turn off the SEI frame. SEI is an information given by the encoder to the decoder, it has it is usefull for the decoder.

**Comment by daveisfera** [comment]
Sorry, I mean can the camera/encoder be run in a different mode so that the SEI isn't sent? When recording a video to a file, this is happening, so it seems like something that should be possible when streaming to the RTMP server as well.

**Comment by ThibaultBee** [comment]
Well, it is possible to drop it when the encoder generates it but we won't do it. SEI is a standard message, there are no reason it is not understand by the decoder. What server do you use?

**Comment by ThibaultBee** [comment]
There are no controls for that in this RN library. If you are looking in a workaround, you can focus on the iOS native library we use: HaishinKit. Have a look in this code, there might be a way to drop the SEI.
