### ISSUE TITLE
A way to capture an image while user's broadcasting

### ISSUE THREAD

**Issue by soemarko** [apivideo/api.video-reactnative-live-stream#53]
As titled, it seems that I can use [react-native-view-shot](https://www.npmjs.com/package/react-native-view-shot) on iOS, but it failed on Android (I also open an issue there). Would be great if I don't need to add another dependencies.

**Comment by ThibaultBee** [comment]
Hi,

I am not going to lie, we are not going to work on this in the following year, because it is a lot of work to implement (as the native libraries does not support it) and it may interest less than 1% of the developer using this library. Also, at api.video, we already have a realllllly busy roadmap.

If the native libraries implement this it would be easy, unfortunately they doesn't. 
If you (or anyone) want to tackle this subject, we will be glad to help and to review the PR.

Best regards,
Thibault
