### ISSUE TITLE
zoom feature 

### ISSUE THREAD

**Issue by nimajnsr** [apivideo/api.video-reactnative-live-stream#9]
it would be great if you guys add zoom feature as well

**Comment by nimajnsr** [comment]
> We have done some initial work on this already. A zoom integration is in our backlog and we will be discussing how to add it to our roadmap in the near future!

any updates?

**Comment by ThibaultBee** [comment]
Hi,

I believe there has been a misunderstand. @zenibandy talked about an api.video [Zoom Meeting](https://explore.zoom.us/fr/products/meetings/) plugin whereas you were talking about a camera zoom.
Unfortunately, the camera zoom is not a short term feature. There hasn't been any progress because we are focusing on other api.video projects or adding features that are mandatory to existent projects. If you are in a hurry, you can contribute and submit a PR to our projects. In this case, tell us we will give you few tips and infos.

Best regards,
Thibaukt

**Comment by BlueBazze** [comment]
Its a fairly easy implementation on both Android & iOS.
But you will quickly run into issues.
When i first tried it with native zoom. The controls which were positioned absolute over the preview. Meaning the controls had a view that was catching the gesture events.
A slightly worse way to implement it would be to use React Native Gesture Handler. Having a prop that takes a controls component that you render on top of the preview. Wrapping that with a gesture handler, and using the setNativeProps function so you are not updating the component on every gesture tick. - This way can feel a little unnatural because you sometimes experience a slight delay from gesture to reaction (The zoom value has to go through the RN bridge which introduces the delay).

**Comment by ThibaultBee** [comment]
Hi,
Thank you for your remark. :)
I believe you are refering to the example code. We are aware it is not flawless but we want to provide the best experience for  developers. Currently, we got other focuses but we added it to our TODO list.

**Comment by ThibaultBee** [comment]
See https://github.com/apivideo/api.video-reactnative-live-stream/pull/32

**Comment by ThibaultBee** [comment]
Zoom on pinch and set zoom ratio is supported since 1.2.0
